### ISSUE TITLE
Customize Import Filter

### ISSUE THREAD

**Issue by Micronarrativ** [dsoulayrol/android-sholi#21]
Hi,

I using heavily the import function to get the shopping lists from other applications (or manually created ones) into the application. However: manual lists and lists created from other applications do not necessarily use the same list syntax as sholi, which requires search/replace steps to import the lists.
A dialog to set or specify the list separator (e.g. '*', '-', '+' etc.) would be helpful.
I could change it in the code and re-compile (I guess), but a) the separator changes from list to list and this might be actually useful for other people using this nice app as well.
Thanks.

**Comment by dsoulayrol** [comment]
Hi.

I never thought about this. I am curious to learn what formats you have encountered to see if I can provide a clean and interesting support for different ways to export or import data. Note that the format used by Sholi embeds the status of the items in the list separator, as described in https://github.com/dsoulayrol/android-sholi/blob/master/doc/manual.md.

**Comment by Micronarrativ** [comment]
Hi,

the first time I encountered this was when I wrote a shopping list just in markdown and used the asterisk (*) as the list symbol. That obviously failed. I still write the lists in Markdown, but replace the list symbol from '*' to '-' on the phone with an editor.  
When exporting a list from other applications, I've seen so far all sorts of combinations used a list symbols:

* '#'
* '-'
* '+'

Basically, whatever you can come up with is being used. Partly I use it with exported data from "food-sites" where you pick you meal and it tells you what you need to shop. Those lists I import into _sholi_.
The list symbol _sholi_ is using makes imho sense within the context of the application, but requires to stick exactly to the listing syntax. That requires - at least for me - to replace the listing symbol in the lists I want to import before I can actually do that. Doesn't seem like anyone else has used this in combination with exported data from other sources?

**Comment by dsoulayrol** [comment]
Hello.

As I wrote earlier, Sholi computes the status of one item (the item is *checked*, *listed* or *unlisted*) using its list symbol on import (and choose the symbol matching the item status on export). So, the better way I imagine to fit with your requirement is to provide a custom setting for each symbol used in import and export data. Default would be the current `*` for unlited items, `-` for listed items and `+` for checked ones.

It may be possible to define any string, and not just a symbol. Thus, the following list could be imported if, for example, `ingredient` is defined for listed items, and `spice` for unlisted items.

    ingredient bread
    ingredient ham
    ingredient pickle
    ingredient salad
    spice mustard
    spice ketchup
    spice napkin
    spice fork

When the symbols are configured, Sholi must check that they do not overlap: for now, I want that one symbol still represent only one item state, so that there is no loss of information on export and no indecision on import. Documentation must be updated according to this new behaviour.

The export and import features were primarily a great tool for development when I need to do tests which implies to recreate the database. I am happy they are useful in a context I did not imagine. :)

**Comment by Micronarrativ** [comment]
Yes, I think we mean both the same here. Defining a string instead of only a single character would even go further to what I had thought ( and currently use) of.
Is this something you would do? I would consider doing it myself if a) I would be an android programmer or b) if it would bother me enough to make me one.

btw: the way the import function ignores all other lines works just perfect. Storing a whole recipe in a textfile this allows me to import the whole file and only the listed items (basically the ingredians == what to shop) gets imported. It could not be easier. Thx.

**Comment by dsoulayrol** [comment]
This is something I am interested in adding to Sholi. I will do it when I have a moment.

**Comment by Micronarrativ** [comment]
Hi, I just saw the latest update and wanted to say thank you for the implementation of this specific feature! Thanks a lot.
